#!/bin/bash
# Master submit script generated by Python
# This finds every qe.sub in the subdirectories and submits them

BASE_DIR="./"

# Use find to catch qe.sub even if they are inside scf_0 subfolders
find "$BASE_DIR" -name "qe.sub" | while read sub_file; do
    dir=$(dirname "$sub_file")
    echo "Submitting job in $dir"

    # Use -D to tell sbatch to run FROM that directory
    sbatch -D "$dir" "$sub_file"
done

echo "All jobs submitted. Check status with: squeue -u $USER"
